# [Template] Create NuGet packages.

parameters:
  version: '$(MRTKVersion)-$(Build.BuildNumber)'
  packDestination: '$(Build.SourcesDirectory)/artifacts'

steps:
- task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2  # NuGetCommand
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: 'NuGet/**/*.nuspec'
    packDestination: ${{ parameters.packDestination }}
    buildProperties: 'version=${{ parameters.version }}'
