name: Code Validation (MRTK2)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  validation:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Pull Request changes
      if: github.event_name == 'pull_request'
      run: |
        ./scripts/ci/gitchanges.ps1 -TargetBranch '${{ github.base_ref }}' -OutputFile '${{ runner.temp }}/build/changed_files.txt' -RepoRoot '${{ github.workspace }}'
      shell: pwsh

    - name: Scoped code validation
      if: github.event_name == 'pull_request'
      run: |
        ./scripts/ci/validatecode.ps1 -Directory '${{ github.workspace }}/Assets' -ChangesFile '${{ runner.temp }}/build/changed_files.txt' -RepoRoot '${{ github.workspace }}'
      shell: pwsh

    # todo: uncomment when #8944 is implemented
    # - name: Scoped asset dependency validation
    #   if: github.event_name == 'pull_request'
    #   run: |
    #     ./scripts/ci/validateassets.ps1 -Directory '${{ github.workspace }}/Assets' -ChangesFile '${{ runner.temp }}/build/changed_files.txt' -RepoRoot '${{ github.workspace }}'
    #   shell: pwsh

    - name: Global code validation
      if: github.event_name == 'push'
      run: |
        ./scripts/ci/validatecode.ps1 -Directory '${{ github.workspace }}/Assets'
      shell: pwsh

    - name: Global asset dependency validation
      # todo: uncomment when #8944 is implemented
      # if: github.event_name == 'push'
      run: |
        ./scripts/ci/validateassets.ps1 -Directory '${{ github.workspace }}/Assets'
      shell: pwsh
