name: Code Validation (MRTK3)

on:
  push:
    branches: [ "mrtk3" ]
  pull_request:
    branches: [ "mrtk3" ]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Pull Request changes
      if: github.event_name == 'pull_request'
      run: |
        ./pipelines/scripts/gitchanges.ps1 -TargetBranch '${{ github.base_ref }}' -OutputFile '${{ runner.temp }}/build/changed_files.txt' -RepoRoot '${{ github.workspace }}'
      shell: pwsh

    - name: Scoped code validation
      if: github.event_name == 'pull_request'
      run: |
        ./pipelines/scripts/validatecode.ps1 -Directory '${{ github.workspace }}' -ChangesFile '${{ runner.temp }}/build/changed_files.txt'
      shell: pwsh

    - name: Global code validation
      if: github.event_name == 'push'
      run: |
        ./pipelines/scripts/validatecode.ps1 -Directory '${{ github.workspace }}'
      shell: pwsh

    - name: Lint
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: mrtk3
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}